language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
install: "pip install -r requirements-dev.txt"
script: py.test -v --cov=./
after_success:
  - codecov
